// Generated by CoffeeScript 1.6.3
(function() {
  var abc;

  abc = function() {
    var a, b, c, r, sum;
    sum = 1000;
    a = void 0;
    a = 1;
    while (a <= sum / 3) {
      b = void 0;
      b = a + 1;
      while (b <= sum / 2) {
        c = sum - a - b;
        if (c > 0 && (a * a + b * b === c * c)) {
          r = a * b * c;
          return r;
        }
        b++;
      }
      a++;
    }
  };

  console.log(abc());

}).call(this);
