// Generated by CoffeeScript 1.6.3
(function() {
  var abc, def, xyz;

  abc = function() {
    var i, j, sm;
    i = void 0;
    j = 0;
    sm = 0;
    i = 1;
    while (i <= 100) {
      j = i * i;
      sm = sm + j;
      i++;
    }
    return sm;
    return console.log(sm);
  };

  def = function() {
    var i, j, sm;
    i = void 0;
    j = 0;
    sm = 0;
    i = 1;
    while (i <= 100) {
      sm = sm + i;
      i++;
    }
    j = sm * sm;
    return j;
    return console.log(j);
  };

  xyz = function() {
    var a;
    a = def() - abc();
    return a;
  };

  console.log(xyz());

}).call(this);
