// Generated by CoffeeScript 1.6.3
(function() {
  var abc;

  abc = function() {
    var i, sum;
    sum = 0;
    i = 1;
    while (i < 1000) {
      if ((i % 5 === 0) || (i % 3 === 0)) {
        sum = sum + i;
      }
      i++;
    }
    return sum;
  };

  document.write(abc());

}).call(this);
