// Generated by CoffeeScript 1.6.3
(function() {
  var abc;

  abc = function(num) {
    var i, j, k, t;
    i = 1;
    j = void 0;
    k = void 0;
    t = 0;
    while (i <= num) {
      k = 0;
      if (num % i === 0) {
        j = 1;
        while (j <= i) {
          if (i % j === 0) {
            k++;
          }
          j++;
        }
        if (k === 2 ? t <= i : void 0) {
          t = i;
        }
      }
      i++;
    }
    return console.log(t);
  };

  abc(600851475143);

}).call(this);
