// Generated by CoffeeScript 1.6.3
(function() {
  var type,
    __slice = [].slice;

  type = ["node", "docco", "express", "backbone", "coffee", "cake"];

  ilike(function() {
    var most, rest, second;
    most = arguments[0], second = arguments[1], rest = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
    alert("I like (#most) the most");
    alert("I like (#second) the second most");
    return alert("I also like (#rest)");
  });

  I.apply(null, liketype);

}).call(this);
